# Adjacency Matrix Structure - Estructura de Matriz de Adyacencia

Realice lo siguiente:
  * Programe la representación de grafos mediante un la **Estructura de Matriz de Adyacencia**.
  * Mediante networkx muestre el resultado gráfico del gráfo.

In [21]:
import numpy

def weighted_adjmatrix(adjlist, nodes):
    '''Returns a (weighted) adjacency matrix as a NumPy array.'''
    matrix = []
    for node in nodes:
        weights = {endnode:int(weight)
                   for w in adjlist.get(node, {})
                   for endnode, weight in w.items()}
        matrix.append([weights.get(endnode, 0) for endnode in nodes])
    matrix = numpy.array(matrix)
    return matrix + matrix.transpose()

graph = {'1': [{'2':'15'}, {'4':'7'}, {'5':'10'}],
    '2': [{'3':'9'}, {'4':'11'}, {'6':'9'}],
    '3': [{'5':'12'}, {'6':'7'}],
    '4': [{'5':'8'}, {'6':'14'}],
    '5': [{'6':'8'}]}
a = weighted_adjmatrix(graph,nodes=list('123456'))
print(a)

[[ 0 15  0  7 10  0]
 [15  0  9 11  0  9]
 [ 0  9  0  0 12  7]
 [ 7 11  0  0  8 14]
 [10  0 12  8  0  8]
 [ 0  9  7 14  8  0]]
